[package]
name = "frontend"
version = "0.1.0"
edition = "2024"

[dependencies]
async-std.workspace = true
gtk.workspace = true
regex.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
url_resolver = { path = "../url_resolver" }
utils = { path = "../utils" }
