[package]
name = "frontend"
version = "0.1.1"
edition = "2024"

[dependencies]
async-std.workspace = true
backend.workspace = true
gtk4.workspace = true
sqlx.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
utils.workspace = true
