[workspace]
resolver = "3"
members = ["dns_provider", "frontend", "utils"]

[workspace.dependencies]
gtk = { version = "0.9.7", package = "gtk4", features = ["v4_18"] }
regex = "1.11.1"
async-std = { version = "1.13.1", features = ["attributes"] }
sqlx = { version = "0.8.6", features = ["mysql", "runtime-async-std"] }
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
