[workspace]
resolver = "3"
members = [
    "backend",
    "dns_cacher",
    "dns_provider",
    "frontend",
    "server",
    "utils",
]

[workspace.dependencies]
async-std = { version = "1.13.1", features = ["attributes"] }
futures = "0.3.31"
gtk = { version = "0.9.7", package = "gtk4", features = ["v4_18"] }
regex = "1.11.1"
shlex = "1.3.0"
sqlx = { version = "0.8.6", features = ["mysql", "runtime-async-std"] }
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
