[package]
name = "backend"
version = "0.1.1"
edition = "2024"

[dependencies]
async-std.workspace = true
futures.workspace = true
gtk4.workspace = true
sqlx.workspace = true
libloading.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
utils.workspace = true
