[package]
name = "server"
version = "0.1.0"
edition = "2024"
default-run = "server"

[dependencies]
async-std.workspace = true
shlex.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
utils = { path = "../utils" }
