[package]
name = "dns_provider"
version = "0.1.0"
edition = "2024"
default-run = "dns_provider"

[dependencies]
async-std.workspace = true
sqlx.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
