[package]
name = "dns_cacher"
version = "0.1.1"
edition = "2024"

[dependencies]
async-std.workspace = true
sqlx.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
utils.workspace = true
