[package]
name = "url_resolver"
version = "0.1.0"
edition = "2024"

[dependencies]
async-std.workspace = true
futures.workspace = true
gtk.workspace = true
sqlx.workspace = true
libloading.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
utils.workspace = true
